version: '3.5'

services:
  admin:
    build:
      context: ./admin/
    volumes:
      - ./admin/:/app:cached

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
